import type { ToolDefinition } from './tool-schema.js';

type OutputSchema = NonNullable<ToolDefinition['outputSchema']>;

const str = (description?: string) => ({ type: 'string', ...(description ? { description } : {}) });
const num = (description?: string) => ({ type: 'number', ...(description ? { description } : {}) });
const bool = (description?: string) => ({ type: 'boolean', ...(description ? { description } : {}) });
const arr = (items: Record<string, unknown>, description?: string) => ({
  type: 'array',
  items,
  ...(description ? { description } : {}),
});
const obj = (properties: Record<string, unknown>, description?: string): OutputSchema => ({
  type: 'object',
  properties,
  ...(description ? { description } : {}),
});

const trueSolarTimeSchema = obj({
  clockTime: str('钟表时间'),
  trueSolarTime: str('真太阳时'),
  longitude: num('经度'),
  correctionMinutes: num('校正分钟数'),
}, '真太阳时信息');

const hiddenStemSchema = obj({
  stem: str('藏干天干'),
  tenGod: str('藏干十神'),
  qiType: str('气性'),
});

const branchRelationSchema = obj({
  type: str('关系类型'),
  branches: arr(str(), '涉及地支'),
  description: str('关系描述'),
});

const liunianItemSchema = obj({
  year: num('流年年份'),
  age: num('年龄'),
  ganZhi: str('干支'),
  gan: str('天干'),
  zhi: str('地支'),
  tenGod: str('天干十神'),
  nayin: str('纳音'),
  hiddenStems: arr(hiddenStemSchema, '藏干'),
  diShi: str('地势'),
  shenSha: arr(str(), '神煞'),
  branchRelations: arr(branchRelationSchema, '地支关系'),
  taiSui: arr(str(), '太岁关系'),
});

const dayunItemSchema = obj({
  startYear: num('起始年份'),
  startAge: num('起运年龄'),
  ganZhi: str('干支'),
  stem: str('天干'),
  branch: str('地支'),
  tenGod: str('十神'),
  branchTenGod: str('地支主气十神'),
  hiddenStems: arr(hiddenStemSchema, '藏干'),
  diShi: str('地势'),
  naYin: str('纳音'),
  shenSha: arr(str(), '神煞'),
  branchRelations: arr(branchRelationSchema, '原局关系'),
  liunianList: arr(liunianItemSchema, '流年列表'),
});

export const canonicalOutputSchemas: Record<string, OutputSchema> = {
  bazi_calculate: obj({
    基本信息: obj({
      性别: str('性别'),
      日主: str('日主'),
      命主五行: str('命主五行'),
      空亡: arr(str(), '空亡'),
      出生地: str('出生地'),
      真太阳时: obj({
        钟表时间: str('钟表时间'),
        真太阳时: str('真太阳时'),
        经度: num('经度'),
        校正分钟: num('校正分钟'),
      }),
      胎元: str('胎元'),
      命宫: str('命宫'),
    }),
    四柱: arr(obj({
      柱: str('柱名'),
      干支: str('干支'),
      天干十神: str('十神'),
      藏干: arr(obj({
        天干: str('藏干天干'),
        十神: str('藏干十神'),
        气性: str('气性'),
      })),
      地势: str('地势'),
      纳音: str('纳音'),
      神煞: arr(str()),
      空亡: str('是否空亡'),
    }), '四柱'),
    干支关系: arr(str(), '干支关系'),
    大运: obj({
      起运信息: str('起运信息'),
      大运列表: arr(obj({
        起运年份: num('起始年份'),
        起运年龄: num('起运年龄'),
        干支: str('干支'),
        天干: str('天干'),
        地支: str('地支'),
        十神: str('十神'),
        地支主气十神: str('地支主气十神'),
        藏干: arr(obj({
          天干: str('藏干天干'),
          十神: str('藏干十神'),
          气性: str('气性'),
        })),
        地势: str('地势'),
        纳音: str('纳音'),
        神煞: arr(str(), '神煞'),
        原局关系: arr(obj({
          类型: str('关系类型'),
          地支: arr(str(), '涉及地支'),
          描述: str('关系描述'),
        }), '原局关系'),
        流年列表: arr(obj({
          流年: num('流年年份'),
          年龄: num('年龄'),
          干支: str('干支'),
          天干: str('天干'),
          地支: str('地支'),
          十神: str('十神'),
          纳音: str('纳音'),
          藏干: arr(obj({
            天干: str('藏干天干'),
            十神: str('藏干十神'),
            气性: str('气性'),
          })),
          地势: str('地势'),
          神煞: arr(str(), '神煞'),
          原局关系: arr(obj({
            类型: str('关系类型'),
            地支: arr(str(), '涉及地支'),
            描述: str('关系描述'),
          }), '原局关系'),
          太岁关系: arr(str(), '太岁关系'),
        }), '流年列表'),
      }), '大运列表'),
    }),
  }),
  bazi_pillars_resolve: obj({
    originalPillars: obj({
      yearPillar: str('年柱'),
      monthPillar: str('月柱'),
      dayPillar: str('日柱'),
      hourPillar: str('时柱'),
    }),
    count: num('候选总数'),
    candidates: arr(obj({
      candidateId: str('候选ID'),
      lunarText: str('农历文本'),
      solarText: str('公历文本'),
      birthTime: str('出生时间'),
      isLeapMonth: bool('是否闰月'),
    })),
  }),
  bazi_dayun: obj({
    起运信息: obj({
      起运年龄: num('起运年龄'),
      起运详情: str('起运详情'),
    }),
    小运: arr(obj({
      年龄: num('年龄'),
      干支: str('干支'),
      十神: str('天干十神'),
    }), '小运列表'),
    大运列表: arr(obj({
      起运年份: num('起始年份'),
      起运年龄: num('起运年龄'),
      干支: str('干支'),
      天干: str('天干'),
      地支: str('地支'),
      十神: str('十神'),
      地支主气十神: str('地支主气十神'),
      藏干: arr(obj({
        天干: str('藏干天干'),
        十神: str('藏干十神'),
        气性: str('气性'),
      })),
      地势: str('地势'),
      纳音: str('纳音'),
      神煞: arr(str(), '神煞'),
      原局关系: arr(obj({
        类型: str('关系类型'),
        地支: arr(str(), '涉及地支'),
        描述: str('关系描述'),
      }), '原局关系'),
      流年列表: arr(obj({
        流年: num('流年年份'),
        年龄: num('年龄'),
        干支: str('干支'),
        天干: str('天干'),
        地支: str('地支'),
        十神: str('十神'),
        纳音: str('纳音'),
        藏干: arr(obj({
          天干: str('藏干天干'),
          十神: str('藏干十神'),
          气性: str('气性'),
        })),
        地势: str('地势'),
        神煞: arr(str(), '神煞'),
        原局关系: arr(obj({
          类型: str('关系类型'),
          地支: arr(str(), '涉及地支'),
          描述: str('关系描述'),
        }), '原局关系'),
        太岁关系: arr(str(), '太岁关系'),
      }), '流年列表'),
    }), '大运列表'),
  }),
  ziwei_calculate: obj({
    基本信息: obj({
      性别: str('性别'),
      阳历: str('阳历'),
      农历: str('农历'),
      四柱: str('四柱'),
      命主: str('命主'),
      身主: str('身主'),
      五行局: str('五行局'),
      生年四化: obj({
        天干: str('生年天干'),
        四化星曜: arr(obj({
          四化: str('四化'),
          星曜: str('星曜'),
          宫位: str('所在宫位'),
        }), '生年四化'),
      }, '生年四化'),
      时辰: str('时辰'),
      斗君: str('斗君'),
      命主星: str('命主星'),
      身主星: str('身主星'),
      真太阳时: obj({
        钟表时间: str('钟表时间'),
        真太阳时: str('真太阳时'),
        经度: num('经度'),
        校正分钟: num('校正分钟'),
        真太阳时索引: num('真太阳时索引'),
        跨日偏移: str('跨日偏移'),
      }, '真太阳时'),
    }),
    十二宫位: arr(obj({
      宫位: str('宫位'),
      宫位索引: num('宫位索引'),
      干支: str('干支'),
      是否身宫: str('是否身宫'),
      是否来因宫: str('是否来因宫'),
      大限: str('大限'),
      主星及四化: arr(obj({
        星名: str('星名'),
        亮度: str('亮度'),
        四化: str('四化'),
        离心自化: str('离心自化'),
        向心自化: str('向心自化'),
      })),
      辅星: arr(obj({
        星名: str('星名'),
        亮度: str('亮度'),
        四化: str('四化'),
        离心自化: str('离心自化'),
        向心自化: str('向心自化'),
      })),
      杂曜: arr(obj({
        星名: str('星名'),
        亮度: str('亮度'),
        四化: str('四化'),
        离心自化: str('离心自化'),
        向心自化: str('向心自化'),
      })),
      神煞: arr(str(), '神煞'),
      流年虚岁: arr(num(), '流年虚岁'),
      小限虚岁: arr(num(), '小限虚岁'),
    }), '十二宫'),
    小限: arr(obj({
      宫位: str('宫位'),
      虚岁: arr(num(), '虚岁列表'),
    }), '小限'),
  }),
  ziwei_horoscope: obj({
    基本信息: obj({
      目标日期: str('目标日期'),
      五行局: str('五行局'),
      阳历: str('阳历'),
      农历: str('农历'),
      命主: str('命主'),
      身主: str('身主'),
    }),
    运限叠宫: arr(obj({
      层次: str('层次'),
      时间段备注: str('时间段或备注'),
      宫位索引: num('宫位索引'),
      干支: str('干支'),
      落入本命宫位: str('落入本命宫位'),
      运限四化: arr(str(), '运限四化'),
      十二宫重排: arr(str(), '十二宫重排'),
    })),
    流年星曜: obj({
      吉星分布: arr(str(), '吉星分布'),
      煞星分布: arr(str(), '煞星分布'),
      '桃花/文星': arr(str(), '桃花/文星'),
    }),
    岁前十二星: arr(str(), '岁前十二星'),
    将前十二星: arr(str(), '将前十二星'),
  }),
  ziwei_flying_star: obj({
    查询结果: arr(obj({
      查询序号: num('查询序号'),
      查询类型: str('查询类型'),
      判断目标: str('判断目标'),
      结果: str('结果'),
      发射宫位: str('发射宫位'),
      发射宫干支: str('发射宫干支'),
      实际飞化: arr(obj({
        四化: str('四化'),
        宫位: str('目标宫位'),
        星曜: str('星曜'),
      })),
      四化落宫: arr(obj({
        四化: str('四化'),
        宫位: str('目标宫位'),
        星曜: str('星曜'),
      })),
      本宫: str('本宫'),
      矩阵宫位: obj({
        对宫: str('对宫'),
        三合1: str('三合宫1'),
        三合2: str('三合宫2'),
      }),
    })),
  }),
  liuyao: obj({
    卦盘: obj({
      问题: str('问题'),
      本卦: obj({
        卦名: str('本卦'),
        卦宫: str('卦宫'),
        五行: str('五行'),
        卦辞: str('卦辞'),
      }),
      变卦: obj({
        卦名: str('变卦'),
        卦宫: str('卦宫'),
        五行: str('五行'),
        卦辞: str('卦辞'),
        动爻: arr(str(), '动爻'),
        动爻爻辞: arr(obj({
          爻名: str('爻名'),
          爻辞: str('爻辞'),
        }), '动爻爻辞'),
      }),
      干支时间: arr(obj({
        柱: str('柱'),
        干支: str('干支'),
        空亡: arr(str(), '空亡'),
      })),
      卦身: obj({
        地支: str('卦身地支'),
        位置: str('位置'),
        状态: str('状态'),
      }),
      衍生卦: obj({
        互卦: obj({ 卦名: str('互卦') }),
        错卦: obj({ 卦名: str('错卦') }),
        综卦: obj({ 卦名: str('综卦') }),
      }),
      全局神煞: arr(str(), '全局神煞'),
    }),
    六爻全盘: obj({
      爻列表: arr(obj({
        爻位: str('爻位'),
        六神: str('六神'),
        神煞: arr(str(), '神煞'),
        伏神: obj({
          六亲: str('伏神六亲'),
          纳甲: str('伏神纳甲'),
          五行: str('伏神五行'),
        }),
        本爻: obj({
          六亲: str('本卦六亲'),
          纳甲: str('本卦纳甲'),
          五行: str('本卦五行'),
          旺衰: str('旺衰'),
        }),
        动静: str('动静'),
        空亡: str('空亡'),
        变爻: obj({
          六亲: str('变出六亲'),
          纳甲: str('变出纳甲'),
          五行: str('变出五行'),
        }),
        化变: str('化变'),
        世应: str('世应'),
      }), '六爻全盘'),
    }),
    全局互动: obj({
      组合关系: arr(obj({
        类型: str('互动类型'),
        结果五行: str('结果五行'),
        参与者: arr(obj({
          来源: str('参与来源'),
          地支: str('地支'),
          位置: str('位置'),
        }), '参与者'),
        名称: str('组合名'),
        位置: arr(str(), '位置'),
      }), '组合关系'),
      冲合转换: arr(obj({
        类型: str('转换类型'),
      }), '冲合转换'),
      反伏信息: arr(obj({
        类型: str('共振类型'),
      }), '反吟伏吟'),
      是否六冲卦: str('是否六冲卦'),
      是否六合卦: str('是否六合卦'),
      冲合趋势: str('冲合转换'),
    }),
    元信息: obj({
      细节级别: str('细节级别'),
    }),
  }),
  tarot: obj({
    问卜设定: obj({
      牌阵: str('牌阵'),
      问题: str('问题'),
      出生日期: str('出生日期'),
      随机种子: str('随机种子'),
    }),
    牌阵展开: arr(obj({
      位置: str('位置'),
      塔罗牌: str('塔罗牌'),
      状态: str('状态'),
      核心基调: arr(str(), '核心基调'),
      元素: str('元素'),
      星象: str('星象对应'),
    })),
    求问者生命数字: obj({
      人格牌: obj({
        对应塔罗: str('人格牌'),
        背景基调: arr(str(), '背景基调'),
        元素: str('元素'),
        星象: str('星象对应'),
      }),
      灵魂牌: obj({
        对应塔罗: str('灵魂牌'),
        背景基调: arr(str(), '背景基调'),
        元素: str('元素'),
        星象: str('星象对应'),
      }),
      年度牌: obj({
        对应塔罗: str('年度牌'),
        年份: num('年份'),
        背景基调: arr(str(), '背景基调'),
        元素: str('元素'),
        星象: str('星象对应'),
      }),
    }),
  }),
  almanac: obj({
    基础与个性化坐标: obj({
      日期: str('日期'),
      日干支: str('日干支'),
      流日十神: str('流日十神'),
    }),
    传统黄历基调: obj({
      农历: str('农历'),
      生肖: str('生肖'),
      节气: str('节气'),
      冲煞: str('冲煞'),
      彭祖百忌: str('彭祖百忌'),
      胎神占方: str('胎神'),
      日九星: obj({
        描述: str('描述'),
        方位: str('方位'),
      }),
    }),
    择日宜忌: obj({
      宜: arr(str(), '宜'),
      忌: arr(str(), '忌'),
    }),
    神煞参考: obj({
      吉神宜趋: arr(str(), '吉神'),
      凶煞宜忌: arr(str(), '凶煞'),
    }),
    方位信息: obj({
      财神: str('财神'),
      喜神: str('喜神'),
      福神: str('福神'),
      阳贵人: str('阳贵人'),
      阴贵人: str('阴贵人'),
    }),
    值日信息: obj({
      建除十二值星: str('建除十二值星'),
      天神: str('天神'),
      天神类型: str('天神类型'),
      天神吉凶: str('天神吉凶'),
      二十八星宿: str('二十八星宿'),
      星宿吉凶: str('星宿吉凶'),
      星宿歌诀: str('星宿歌诀'),
      日柱纳音: str('日柱纳音'),
    }),
    时辰吉凶: arr(obj({
      时辰: str('时辰'),
      天神: str('天神'),
      天神类型: str('天神类型'),
      天神吉凶: str('天神吉凶'),
      冲煞: str('冲煞'),
      宜: arr(str(), '宜'),
      忌: arr(str(), '忌'),
    })),
  }),
  qimen_calculate: obj({
    基本信息: obj({
      占问: str('占问'),
      四柱: str('四柱'),
      节气: str('节气'),
      局式: str('局式'),
      三元: str('三元'),
      旬首: str('旬首'),
      值符: str('值符'),
      值使: str('值使'),
      公历: str('公历'),
      农历: str('农历'),
      节气范围: str('节气范围'),
      盘式: str('盘式'),
      定局法: str('定局法'),
    }),
    九宫盘: arr(obj({
      宫名: str('宫名'),
      宫位序号: num('宫位序号'),
      宫位: str('宫位'),
      宫位五行: str('宫位五行'),
      八神: str('八神'),
      九星: str('九星'),
      九星五行: str('九星五行'),
      八门: str('八门'),
      八门五行: str('八门五行'),
      天盘天干: str('天盘天干'),
      地盘天干: str('地盘天干'),
      宫位状态: arr(str(), '宫位状态'),
      方位: str('方位'),
      格局: arr(str(), '格局'),
      宫旺衰: str('宫旺衰'),
      天盘天干五行: str('天盘天干五行'),
      地盘天干五行: str('地盘天干五行'),
    })),
    空亡信息: obj({
      日空: obj({
        地支: arr(str(), '地支'),
        宫位: arr(str(), '宫位'),
      }),
      时空: obj({
        地支: arr(str(), '地支'),
        宫位: arr(str(), '宫位'),
      }),
    }),
    驿马: obj({
      地支: str('驿马地支'),
      宫位: str('驿马宫位'),
    }),
    十干月令旺衰: {
      type: 'object',
      description: '十干月令旺衰',
      additionalProperties: { type: 'string' },
    },
    全局格局: arr(str(), '全局格局'),
  }),
  daliuren: obj({
    基本信息: obj({
      占事: str('占事'),
      占测时间: str('占测时间'),
      昼夜: str('昼夜'),
      四柱: str('四柱'),
      课式: str('课式'),
      月将: str('月将'),
      关键状态: obj({
        空亡: arr(str(), '空亡'),
        驿马: str('驿马'),
        丁马: str('丁马'),
        天马: str('天马'),
      }),
      农历: str('农历'),
      月将名称: str('月将名称'),
      本命: str('本命'),
      行年: str('行年'),
      附加课体: arr(str(), '附加课体'),
    }),
    四课: arr(obj({
      课别: str('课别'),
      乘将: str('乘将'),
      上神: str('上神'),
      下神: str('下神'),
    })),
    三传: arr(obj({
      传序: str('传序'),
      地支: str('地支'),
      天将: str('天将'),
      六亲: str('六亲'),
      遁干: str('遁干'),
    })),
    天地盘: arr(obj({
      地盘: str('地盘'),
      五行: str('五行'),
      旺衰: str('旺衰'),
      天盘: str('天盘'),
      天将: str('天将'),
      遁干: str('遁干'),
      长生十二神: str('长生十二神'),
      建除: str('建除'),
    })),
  }),
};
